// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpAeNkA3T3oOWX9XhY8t29_1vs76ia0w',
    appId: '1:39117304746:web:e28ef0082785c609e831d3',
    messagingSenderId: '39117304746',
    projectId: 'dietic-chat',
    authDomain: 'dietic-chat.firebaseapp.com',
    storageBucket: 'dietic-chat.appspot.com',
    measurementId: 'G-8GKFNCG3GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL4nxn_BChrGLciDclkWex43H0UhkKhOo',
    appId: '1:39117304746:android:0fca8788b29a4c58e831d3',
    messagingSenderId: '39117304746',
    projectId: 'dietic-chat',
    storageBucket: 'dietic-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8QYIublsbXHbeOyTImxeIBt4XNygEKPc',
    appId: '1:39117304746:ios:c4fd283c64aac949e831d3',
    messagingSenderId: '39117304746',
    projectId: 'dietic-chat',
    storageBucket: 'dietic-chat.appspot.com',
    iosClientId: '39117304746-goo9o2k6dq5aa94k169ntfno073gr0j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dieticMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8QYIublsbXHbeOyTImxeIBt4XNygEKPc',
    appId: '1:39117304746:ios:c4fd283c64aac949e831d3',
    messagingSenderId: '39117304746',
    projectId: 'dietic-chat',
    storageBucket: 'dietic-chat.appspot.com',
    iosClientId: '39117304746-goo9o2k6dq5aa94k169ntfno073gr0j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dieticMobil',
  );
}
